
package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * EncounterResultsId generated by hbm2java
 */
public class EncounterResultsId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -8752332694105699175L;
	private int					EId;
	private String				pid1;
	private String				pid2;
	private String				encounterType;
	private String				element;

	public EncounterResultsId ()
	{
	}

	public EncounterResultsId (int EId, String pid1, String pid2, String encounterType, String element)
	{
		this.EId = EId;
		this.pid1 = pid1;
		this.pid2 = pid2;
		this.encounterType = encounterType;
		this.element = element;
	}

	public int getEId ()
	{
		return this.EId;
	}

	public void setEId (int EId)
	{
		this.EId = EId;
	}

	public String getPid1 ()
	{
		return this.pid1;
	}

	public void setPid1 (String pid1)
	{
		this.pid1 = pid1;
	}

	public String getPid2 ()
	{
		return this.pid2;
	}

	public void setPid2 (String pid2)
	{
		this.pid2 = pid2;
	}

	public String getEncounterType ()
	{
		return this.encounterType;
	}

	public void setEncounterType (String encounterType)
	{
		this.encounterType = encounterType;
	}

	public String getElement ()
	{
		return this.element;
	}

	public void setElement (String element)
	{
		this.element = element;
	}

	@Override
	public int hashCode ()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + EId;
		result = prime * result + ((element == null) ? 0 : element.hashCode ());
		result = prime * result + ((encounterType == null) ? 0 : encounterType.hashCode ());
		result = prime * result + ((pid1 == null) ? 0 : pid1.hashCode ());
		result = prime * result + ((pid2 == null) ? 0 : pid2.hashCode ());
		return result;
	}

	@Override
	public boolean equals (Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass () != obj.getClass ())
			return false;
		EncounterResultsId other = (EncounterResultsId) obj;
		if (EId != other.EId)
			return false;
		if (element == null)
		{
			if (other.element != null)
				return false;
		}
		else if (!element.equals (other.element))
			return false;
		if (encounterType == null)
		{
			if (other.encounterType != null)
				return false;
		}
		else if (!encounterType.equals (other.encounterType))
			return false;
		if (pid1 == null)
		{
			if (other.pid1 != null)
				return false;
		}
		else if (!pid1.equals (other.pid1))
			return false;
		if (pid2 == null)
		{
			if (other.pid2 != null)
				return false;
		}
		else if (!pid2.equals (other.pid2))
			return false;
		return true;
	}

	@Override
	public String toString ()
	{
		return EId + ", " + pid1 + ", " + pid2 + ", " + encounterType + ", " + element;
	}

}
