
package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * Definition generated by hbm2java
 */
public class Definition implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 6194730432582510379L;
	private DefinitionId		id;
	private String				definitionValue;

	public Definition ()
	{
	}

	public Definition (DefinitionId id)
	{
		this.id = id;
	}

	public Definition (DefinitionId id, String definitionValue)
	{
		this.id = id;
		this.definitionValue = definitionValue;
	}

	public DefinitionId getId ()
	{
		return this.id;
	}

	public void setId (DefinitionId id)
	{
		this.id = id;
	}

	public String getDefinitionValue ()
	{
		return this.definitionValue;
	}

	public void setDefinitionValue (String definitionValue)
	{
		this.definitionValue = definitionValue;
	}

	@Override
	public String toString ()
	{
		return id + ", " + definitionValue;
	}

}
