
package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * EncounterValue generated by hbm2java
 */
public class EncounterValue implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -6951625702538628749L;
	private EncounterValueId	id;
	private String				consequenceProcedure;

	public EncounterValue ()
	{
	}

	public EncounterValue (EncounterValueId id)
	{
		this.id = id;
	}

	public EncounterValue (EncounterValueId id, String consequenceProcedure)
	{
		this.id = id;
		this.consequenceProcedure = consequenceProcedure;
	}

	public EncounterValueId getId ()
	{
		return this.id;
	}

	public void setId (EncounterValueId id)
	{
		this.id = id;
	}

	public String getConsequenceProcedure ()
	{
		return this.consequenceProcedure;
	}

	public void setConsequenceProcedure (String consequenceProcedure)
	{
		this.consequenceProcedure = consequenceProcedure;
	}

	@Override
	public String toString ()
	{
		return id + ", " + consequenceProcedure;
	}

}
