
package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LogData generated by hbm2java
 */
public class LogData implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 2320428666902479201L;
	private Integer				logId;
	private String				userName;
	private String				logType;
	private Date				dateLogged;
	private String				entity;
	private String				currentValue;

	public LogData ()
	{
	}

	public LogData (String userName, String logType, Date dateLogged, String entity)
	{
		this.userName = userName;
		this.logType = logType;
		this.dateLogged = dateLogged;
		this.entity = entity;
	}

	public LogData (String userName, String logType, Date dateLogged, String entity, String currentValue)
	{
		this.userName = userName;
		this.logType = logType;
		this.dateLogged = dateLogged;
		this.entity = entity;
		this.currentValue = currentValue;
	}

	public Integer getLogId ()
	{
		return this.logId;
	}

	public void setLogId (Integer logId)
	{
		this.logId = logId;
	}

	public String getUserName ()
	{
		return this.userName;
	}

	public void setUserName (String userName)
	{
		this.userName = userName;
	}

	public String getLogType ()
	{
		return logType;
	}

	public void setLogType (String logType)
	{
		this.logType = logType;
	}

	public Date getDateLogged ()
	{
		return this.dateLogged;
	}

	public void setDateLogged (Date dateLogged)
	{
		this.dateLogged = dateLogged;
	}

	public String getEntity ()
	{
		return this.entity;
	}

	public void setEntity (String entity)
	{
		this.entity = entity;
	}

	public String getCurrentValue ()
	{
		return this.currentValue;
	}

	public void setCurrentValue (String currentValue)
	{
		this.currentValue = currentValue;
	}

	@Override
	public String toString ()
	{
		return logId + ", " + userName + ", " + logType + ", " + dateLogged + ", " + entity + ", " + currentValue;
	}

}
