/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * EncounterElement generated by hbm2java
 */
public class EncounterElement implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1039693088057924110L;
	private EncounterElementId	id;
	private String				validator;
	private String				description;

	public EncounterElement ()
	{
	}

	public EncounterElement (EncounterElementId id)
	{
		this.id = id;
	}

	public EncounterElement (EncounterElementId id, String validator, String description)
	{
		this.id = id;
		this.validator = validator;
		this.description = description;
	}

	public EncounterElementId getId ()
	{
		return this.id;
	}

	public void setId (EncounterElementId id)
	{
		this.id = id;
	}

	public String getValidator ()
	{
		return this.validator;
	}

	public void setValidator (String validator)
	{
		this.validator = validator;
	}

	public String getDescription ()
	{
		return this.description;
	}

	public void setDescription (String description)
	{
		this.description = description;
	}

	@Override
	public String toString ()
	{
		return id + ", " + validator + ", " + description;
	}

}
