/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Encounter generated by hbm2java
 */
public class Encounter implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 5837400457336789365L;
	private EncounterId			id;
	private String				locationId;
	private Date				dateStart;
	private Date				dateEnd;
	private Date				dateEntered;
	private String				description;

	public Encounter ()
	{
	}

	public Encounter (EncounterId id, String locationId)
	{
		this.id = id;
		this.locationId = locationId;
	}

	public Encounter (EncounterId id, String locationId, Date dateStart, Date dateEnd, Date dateEntered, String description)
	{
		this.id = id;
		this.locationId = locationId;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.dateEntered = dateEntered;
		this.description = description;
	}

	public EncounterId getId ()
	{
		return this.id;
	}

	public void setId (EncounterId id)
	{
		this.id = id;
	}

	public String getLocationId ()
	{
		return this.locationId;
	}

	public void setLocationId (String locationId)
	{
		this.locationId = locationId;
	}

	public Date getDateStart ()
	{
		return this.dateStart;
	}

	public void setDateStart (Date dateStart)
	{
		this.dateStart = dateStart;
	}

	public Date getDateEnd ()
	{
		return this.dateEnd;
	}

	public void setDateEnd (Date dateEnd)
	{
		this.dateEnd = dateEnd;
	}

	public Date getDateEntered ()
	{
		return this.dateEntered;
	}

	public void setDateEntered (Date dateEntered)
	{
		this.dateEntered = dateEntered;
	}

	public String getDescription ()
	{
		return this.description;
	}

	public void setDescription (String description)
	{
		this.description = description;
	}

	@Override
	public String toString ()
	{
		return id + ", " + locationId + ", " + dateStart + ", " + dateEnd + ", " + dateEntered + ", " + description;
	}
}
