/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 67644268322929447L;
	private int					feedbackId;
	private String				senderId;
	private String				feedbackType;
	private String				feedback;
	private byte[]				attachment;
	private Date				dateReported;
	private String				feedbackStatus;

	public Feedback ()
	{
	}

	public Feedback (String senderId, String feedbackType, String feedback, Date dateReported, String feedbackStatus)
	{
		this.senderId = senderId;
		this.feedbackType = feedbackType;
		this.feedback = feedback;
		this.dateReported = dateReported;
		this.feedbackStatus = feedbackStatus;
	}

	public Feedback (String senderId, String feedbackType, String feedback, byte[] attachment, Date dateReported, String feedbackStatus)
	{
		this.senderId = senderId;
		this.feedbackType = feedbackType;
		this.feedback = feedback;
		this.attachment = attachment;
		this.dateReported = dateReported;
		this.feedbackStatus = feedbackStatus;
	}

	public Integer getFeedbackId ()
	{
		return this.feedbackId;
	}

	public void setFeedbackId (Integer feedbackId)
	{
		this.feedbackId = feedbackId;
	}

	public String getSenderId ()
	{
		return this.senderId;
	}

	public void setSenderId (String senderId)
	{
		this.senderId = senderId;
	}

	public String getFeedbackType ()
	{
		return this.feedbackType;
	}

	public void setFeedbackType (String feedbackType)
	{
		this.feedbackType = feedbackType;
	}

	public String getFeedback ()
	{
		return this.feedback;
	}

	public void setFeedback (String feedback)
	{
		this.feedback = feedback;
	}

	public byte[] getAttachment ()
	{
		return this.attachment;
	}

	public void setAttachment (byte[] attachment)
	{
		this.attachment = attachment;
	}

	public Date getDateReported ()
	{
		return this.dateReported;
	}

	public void setDateReported (Date dateReported)
	{
		this.dateReported = dateReported;
	}

	public String getFeedbackStatus ()
	{
		return this.feedbackStatus;
	}

	public void setFeedbackStatus (String feedbackStatus)
	{
		this.feedbackStatus = feedbackStatus;
	}

	@Override
	public String toString ()
	{
		return feedbackId + ", " + senderId + ", " + feedbackType + ", " + feedback + ", " + Arrays.toString (attachment) + ", " + dateReported + ", " + feedbackStatus;
	}

}
