/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Sep 10, 2012 2:44:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -446647032112863856L;
	private String				locationId;
	private String				locationName;
	private String				locationType;
	private String				address1;
	private String				address2;
	private String				address3;
	private String				address4;
	private String				city;
	private String				state;
	private String				country;
	private String				region;
	private Float				latitude;
	private Float				longitude;
	private String				phone;
	private String				mobile;
	private String				email;
	private String				fax;

	public Location ()
	{
	}

	public Location (String locationId, String locationName, String locationType)
	{
		this.locationId = locationId;
		this.locationName = locationName;
		this.locationType = locationType;
	}

	public Location (String locationId, String locationName, String locationType, String address1, String address2, String address3, String address4, String city, String state, String country,
			String region, Float latitude, Float longitude, String phone, String mobile, String email, String fax)
	{
		this.locationId = locationId;
		this.locationName = locationName;
		this.locationType = locationType;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.address4 = address4;
		this.city = city;
		this.state = state;
		this.country = country;
		this.region = region;
		this.latitude = latitude;
		this.longitude = longitude;
		this.phone = phone;
		this.mobile = mobile;
		this.email = email;
		this.fax = fax;
	}

	public String getLocationId ()
	{
		return this.locationId;
	}

	public void setLocationId (String locationId)
	{
		this.locationId = locationId;
	}

	public String getLocationName ()
	{
		return this.locationName;
	}

	public void setLocationName (String locationName)
	{
		this.locationName = locationName;
	}

	public String getLocationType ()
	{
		return this.locationType;
	}

	public void setLocationType (String locationType)
	{
		this.locationType = locationType;
	}

	public String getAddress1 ()
	{
		return this.address1;
	}

	public void setAddress1 (String address1)
	{
		this.address1 = address1;
	}

	public String getAddress2 ()
	{
		return this.address2;
	}

	public void setAddress2 (String address2)
	{
		this.address2 = address2;
	}

	public String getAddress3 ()
	{
		return this.address3;
	}

	public void setAddress3 (String address3)
	{
		this.address3 = address3;
	}

	public String getAddress4 ()
	{
		return this.address4;
	}

	public void setAddress4 (String address4)
	{
		this.address4 = address4;
	}

	public String getCity ()
	{
		return this.city;
	}

	public void setCity (String city)
	{
		this.city = city;
	}

	public String getState ()
	{
		return this.state;
	}

	public void setState (String state)
	{
		this.state = state;
	}

	public String getCountry ()
	{
		return this.country;
	}

	public void setCountry (String country)
	{
		this.country = country;
	}

	public String getRegion ()
	{
		return this.region;
	}

	public void setRegion (String region)
	{
		this.region = region;
	}

	public Float getLatitude ()
	{
		return this.latitude;
	}

	public void setLatitude (Float latitude)
	{
		this.latitude = latitude;
	}

	public Float getLongitude ()
	{
		return this.longitude;
	}

	public void setLongitude (Float longitude)
	{
		this.longitude = longitude;
	}

	public String getPhone ()
	{
		return this.phone;
	}

	public void setPhone (String phone)
	{
		this.phone = phone;
	}

	public String getMobile ()
	{
		return this.mobile;
	}

	public void setMobile (String mobile)
	{
		this.mobile = mobile;
	}

	public String getEmail ()
	{
		return this.email;
	}

	public void setEmail (String email)
	{
		this.email = email;
	}

	public String getFax ()
	{
		return this.fax;
	}

	public void setFax (String fax)
	{
		this.fax = fax;
	}

	public String toString ()
	{
		return locationId + ", " + locationName + ", " + locationType + ", " + address1 + ", " + address2 + ", " + address3 + ", " + address4 + ", " + city + ", " + state + ", " + country + ", "
				+ region + ", " + latitude + ", " + longitude + ", " + phone + ", " + mobile + ", " + email + ", " + fax;
	}

}
