/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LogLogin generated by hbm2java
 */
public class LogLogin implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 5277266461090323509L;
	private Integer				loginNo;
	private String				userName;
	private Date				dateLogin;
	private Date				dateLogout;
	private String				description;

	public LogLogin ()
	{
	}

	public LogLogin (String userName)
	{
		this.userName = userName;
	}

	public LogLogin (String userName, Date dateLogin, Date dateLogout, String description)
	{
		this.userName = userName;
		this.dateLogin = dateLogin;
		this.dateLogout = dateLogout;
		this.description = description;
	}

	public Integer getLoginNo ()
	{
		return this.loginNo;
	}

	public void setLoginNo (Integer loginNo)
	{
		this.loginNo = loginNo;
	}

	public String getUserName ()
	{
		return this.userName;
	}

	public void setUserName (String userName)
	{
		this.userName = userName;
	}

	public Date getDateLogin ()
	{
		return this.dateLogin;
	}

	public void setDateLogin (Date dateLogin)
	{
		this.dateLogin = dateLogin;
	}

	public Date getDateLogout ()
	{
		return this.dateLogout;
	}

	public void setDateLogout (Date dateLogout)
	{
		this.dateLogout = dateLogout;
	}

	public String getDescription ()
	{
		return this.description;
	}

	public void setDescription (String description)
	{
		this.description = description;
	}

	@Override
	public String toString ()
	{
		return loginNo + ", " + userName + ", " + dateLogin + ", " + dateLogout + ", " + description;
	}

}
