/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -5325075051688496498L;
	private String				pid;
	private String				patientId;
	private String				mrNo;
	private String				externalMrNo;
	private Date				dateScreened;
	private String				suspectedBy;
	private Boolean				diseaseSuspected;
	private Date				dateSuspected;
	private Boolean				diseaseConfirmed;
	private Date				dateConfirmed;
	private String				confirmationSource;
	private String				confirmationRemarks;
	private String				gp;
	private String				treatmentCentre;
	private String				treatmentSupporter;
	private float				weight;
	private float				height;
	private String				bloodGroup;
	private String				diseaseType;
	private String				diseaseCategory;
	private String				diseaseSite;
	private String				treatmentPhase;
	private String				regimenType;
	private String				regimen;
	private float				EDose;
	private float				HDose;
	private float				RDose;
	private float				SDose;
	private float				ZDose;
	private Boolean				streptomycin;
	private Date				dateBaseline;
	private String				patientType;
	private String				patientStatus;
	private Date				dateClosed;
	private String				treatmentOutcome;

	public Patient ()
	{
	}

	public Patient (String pid, String patientId)
	{
		this.pid = pid;
		this.patientId = patientId;
	}

	public Patient (String pid, String patientId, String mrNo, String externalMrNo, Date dateScreened, String suspectedBy, Boolean diseaseSuspected, Date dateSuspected, Boolean diseaseConfirmed,
			Date dateConfirmed, String confirmationSource, String confirmationRemarks, String gp, String treatmentCentre, String treatmentSupporter, float weight, float height, String bloodGroup,
			String diseaseType, String diseaseCategory, String diseaseSite, String treatmentPhase, String regimenType, String regimen, float EDose, float HDose, float RDose, float SDose, float ZDose,
			Boolean streptomycin, Date dateBaseline, String patientType, String patientStatus, Date dateClosed, String treatmentOutcome)
	{
		this.pid = pid;
		this.patientId = patientId;
		this.mrNo = mrNo;
		this.externalMrNo = externalMrNo;
		this.dateScreened = dateScreened;
		this.suspectedBy = suspectedBy;
		this.diseaseSuspected = diseaseSuspected;
		this.dateSuspected = dateSuspected;
		this.diseaseConfirmed = diseaseConfirmed;
		this.dateConfirmed = dateConfirmed;
		this.confirmationSource = confirmationSource;
		this.confirmationRemarks = confirmationRemarks;
		this.gp = gp;
		this.treatmentCentre = treatmentCentre;
		this.treatmentSupporter = treatmentSupporter;
		this.weight = weight;
		this.height = height;
		this.bloodGroup = bloodGroup;
		this.diseaseType = diseaseType;
		this.diseaseCategory = diseaseCategory;
		this.diseaseSite = diseaseSite;
		this.treatmentPhase = treatmentPhase;
		this.regimenType = regimenType;
		this.regimen = regimen;
		this.EDose = EDose;
		this.HDose = HDose;
		this.RDose = RDose;
		this.SDose = SDose;
		this.ZDose = ZDose;
		this.streptomycin = streptomycin;
		this.dateBaseline = dateBaseline;
		this.patientType = patientType;
		this.patientStatus = patientStatus;
		this.dateClosed = dateClosed;
		this.treatmentOutcome = treatmentOutcome;
	}

	public String getPid ()
	{
		return this.pid;
	}

	public void setPid (String pid)
	{
		this.pid = pid;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public String getMrNo ()
	{
		return this.mrNo;
	}

	public void setMrNo (String mrNo)
	{
		this.mrNo = mrNo;
	}

	public String getExternalMrNo ()
	{
		return this.externalMrNo;
	}

	public void setExternalMrNo (String externalMrNo)
	{
		this.externalMrNo = externalMrNo;
	}

	public Date getDateScreened ()
	{
		return this.dateScreened;
	}

	public void setDateScreened (Date dateScreened)
	{
		this.dateScreened = dateScreened;
	}

	public String getSuspectedBy ()
	{
		return this.suspectedBy;
	}

	public void setSuspectedBy (String suspectedBy)
	{
		this.suspectedBy = suspectedBy;
	}

	public Boolean getDiseaseSuspected ()
	{
		return this.diseaseSuspected;
	}

	public void setDiseaseSuspected (Boolean diseaseSuspected)
	{
		this.diseaseSuspected = diseaseSuspected;
	}

	public Date getDateSuspected ()
	{
		return this.dateSuspected;
	}

	public void setDateSuspected (Date dateSuspected)
	{
		this.dateSuspected = dateSuspected;
	}

	public Boolean getDiseaseConfirmed ()
	{
		return this.diseaseConfirmed;
	}

	public void setDiseaseConfirmed (Boolean diseaseConfirmed)
	{
		this.diseaseConfirmed = diseaseConfirmed;
	}

	public Date getDateConfirmed ()
	{
		return this.dateConfirmed;
	}

	public void setDateConfirmed (Date dateConfirmed)
	{
		this.dateConfirmed = dateConfirmed;
	}

	public String getConfirmationSource ()
	{
		return this.confirmationSource;
	}

	public void setConfirmationSource (String confirmationSource)
	{
		this.confirmationSource = confirmationSource;
	}

	public String getConfirmationRemarks ()
	{
		return this.confirmationRemarks;
	}

	public void setConfirmationRemarks (String confirmationRemarks)
	{
		this.confirmationRemarks = confirmationRemarks;
	}

	public String getGp ()
	{
		return this.gp;
	}

	public void setGp (String gp)
	{
		this.gp = gp;
	}

	public String getTreatmentCentre ()
	{
		return this.treatmentCentre;
	}

	public void setTreatmentCentre (String treatmentCentre)
	{
		this.treatmentCentre = treatmentCentre;
	}

	public String getTreatmentSupporter ()
	{
		return this.treatmentSupporter;
	}

	public void setTreatmentSupporter (String treatmentSupporter)
	{
		this.treatmentSupporter = treatmentSupporter;
	}

	public float getWeight ()
	{
		return this.weight;
	}

	public void setWeight (float weight)
	{
		this.weight = weight;
	}

	public float getHeight ()
	{
		return this.height;
	}

	public void setHeight (float height)
	{
		this.height = height;
	}

	public String getBloodGroup ()
	{
		return this.bloodGroup;
	}

	public void setBloodGroup (String bloodGroup)
	{
		this.bloodGroup = bloodGroup;
	}

	public String getDiseaseType ()
	{
		return this.diseaseType;
	}

	public void setDiseaseType (String diseaseType)
	{
		this.diseaseType = diseaseType;
	}

	public String getDiseaseCategory ()
	{
		return this.diseaseCategory;
	}

	public void setDiseaseCategory (String diseaseCategory)
	{
		this.diseaseCategory = diseaseCategory;
	}

	public String getDiseaseSite ()
	{
		return this.diseaseSite;
	}

	public void setDiseaseSite (String diseaseSite)
	{
		this.diseaseSite = diseaseSite;
	}

	public String getTreatmentPhase ()
	{
		return this.treatmentPhase;
	}

	public void setTreatmentPhase (String treatmentPhase)
	{
		this.treatmentPhase = treatmentPhase;
	}

	public String getRegimenType ()
	{
		return this.regimenType;
	}

	public void setRegimenType (String regimenType)
	{
		this.regimenType = regimenType;
	}

	public String getRegimen ()
	{
		return this.regimen;
	}

	public void setRegimen (String regimen)
	{
		this.regimen = regimen;
	}

	public float getEDose ()
	{
		return this.EDose;
	}

	public void setEDose (float EDose)
	{
		this.EDose = EDose;
	}

	public float getHDose ()
	{
		return this.HDose;
	}

	public void setHDose (float HDose)
	{
		this.HDose = HDose;
	}

	public float getRDose ()
	{
		return this.RDose;
	}

	public void setRDose (float RDose)
	{
		this.RDose = RDose;
	}

	public float getSDose ()
	{
		return this.SDose;
	}

	public void setSDose (float SDose)
	{
		this.SDose = SDose;
	}

	public float getZDose ()
	{
		return this.ZDose;
	}

	public void setZDose (float ZDose)
	{
		this.ZDose = ZDose;
	}

	public Boolean getStreptomycin ()
	{
		return this.streptomycin;
	}

	public void setStreptomycin (Boolean streptomycin)
	{
		this.streptomycin = streptomycin;
	}

	public Date getDateBaseline ()
	{
		return this.dateBaseline;
	}

	public void setDateBaseline (Date dateBaseline)
	{
		this.dateBaseline = dateBaseline;
	}

	public String getPatientType ()
	{
		return this.patientType;
	}

	public void setPatientType (String patientType)
	{
		this.patientType = patientType;
	}

	public String getPatientStatus ()
	{
		return this.patientStatus;
	}

	public void setPatientStatus (String patientStatus)
	{
		this.patientStatus = patientStatus;
	}

	public Date getDateClosed ()
	{
		return this.dateClosed;
	}

	public void setDateClosed (Date dateClosed)
	{
		this.dateClosed = dateClosed;
	}

	public String getTreatmentOutcome ()
	{
		return this.treatmentOutcome;
	}

	public void setTreatmentOutcome (String treatmentOutcome)
	{
		this.treatmentOutcome = treatmentOutcome;
	}

	@Override
	public String toString ()
	{
		return pid + ", " + patientId + ", " + mrNo + ", " + externalMrNo + ", " + dateScreened + ", " + suspectedBy + ", " + diseaseSuspected + ", " + dateSuspected + ", " + diseaseConfirmed + ", "
				+ dateConfirmed + ", " + confirmationSource + ", " + confirmationRemarks + ", " + gp + ", " + treatmentCentre + ", " + treatmentSupporter + ", " + weight + ", " + height + ", "
				+ bloodGroup + ", " + diseaseType + ", " + diseaseCategory + ", " + diseaseSite + ", " + treatmentPhase + ", " + regimenType + ", " + regimen + ", " + EDose + ", " + HDose + ", "
				+ RDose + ", " + SDose + ", " + ZDose + ", " + streptomycin + ", " + dateBaseline + ", " + patientType + ", " + patientStatus + ", " + dateClosed + ", " + treatmentOutcome;
	}

}
