/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package com.ihsinformatics.tbreach3tanzania.shared.model;

// Generated Jun 12, 2012 4:08:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * PersonRole generated by hbm2java
 */
public class PersonRole implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -1044966718950828828L;
	private PersonRoleId		id;

	public PersonRole ()
	{
	}

	public PersonRole (PersonRoleId id)
	{
		this.id = id;
	}

	public PersonRoleId getId ()
	{
		return this.id;
	}

	public void setId (PersonRoleId id)
	{
		this.id = id;
	}

	@Override
	public String toString ()
	{
		return String.valueOf (id);
	}

}
